node {

    stage('build') {
        openshiftBuild(buildConfig: 'openshift-test-pipeline-slave', showBuildLogs: 'true')
    }
}

node ('openshift-test-pipeline-slave') {

    stage('test tools') {
        sh("ansible-playbook --version")
        sh("oc version")
    }
}

node {

    stage('promote') {
        openshiftTag(sourceStream: 'openshift-test-pipeline-slave', sourceTag: 'latest', destinationNamespace: 'test-pipeline', destinationStream: 'openshift-test-pipeline-slave', destinationTag: 'latest')
    }
}
