apiVersion: "v1"
kind: "Template"
metadata:
  creationTimestamp: null
  name: "openshift-test-pipeline-template"
objects:
- apiVersion: "build.openshift.io/v1"
  kind: "BuildConfig"
  metadata:
    name: "openshift-test-pipeline"
    labels:
      app: "openshift-test-pipeline"
  spec:
    source:
      git:
        ref: "dev"
        uri: "https://github.com/UKCloud/openshift-test-pipeline"
    strategy:
      jenkinsPipelineStrategy:
        env:
        - name: "RemoteTrigger"
          value: "False"
        - name: "Credentials"
          value: ""
        jenkinsfilePath: "Jenkinsfile"
    triggers:
      - generic:
          allowEnv: true
          secret: ${SECRET}
        type: "Generic"
parameters:
- description: The base64 value used for the generic webhook secret.
  displayName: Secret
  name: SECRET
  required: true